version: '3.4'

services:
  seqLoggerService:
    image: datalust/seq:latest
    container_name: SeqLoggerServiceWebServer
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
      - 50000:5341
    volumes:
      - C:\Docker\Data\SeqJS:/data
    networks:
      - main

networks:
  main:
